[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
scroll = "https://sepolia-rpc.scroll.io"
base = "https://base-rpc.publicnode.com"
# mainnet = "${RPC_MAINNET}" 

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

